name: Build Python module using pip 2

# The CI pipeline build script is currently disabled due to issues with the CUDA installation.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    name: "Build Python module on ${{ matrix.os }} using pip"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: diffdvr
          python-version: 3.12

      - name: Build
        shell: bash -el {0}
        run: |
          export CONDA_ALWAYS_YES="true"
          conda install pytorch torchvision torchaudio cpuonly -c pytorch
